### ISSUE TITLE
Issue in the last web interface version

### ISSUE THREAD

**Issue by altrisi** [DeadmanDungeons/AudioConnect#4]
In the last (or maybe since some ago) version the page where you are connected to a server in to listen the soundtracks of the server, it will not work. The browser tab will show the sound icon, but you can't hear anything. Also, the "sound bars" will be very slow and it will took a bit to remove the soundtrack from the list when leaving the region (when entering it will appear instant). In old versions of the web interface it was working.
Thanks in advance.

## _Tested web interface version:_ 2.2.0

**Comment by JonMcPherson** [comment]
I am unable to reproduce this issue.  I have just tested the web client on Firefox v53, v54, and v55 which all work fine for me.  What operating system are you using?  It probably won't make a difference, but you never know.

**Comment by altrisi** [comment]
Seems it was an issue in 55.0.0. Updated to 55.0.1 (new) and it's now working.
Thanks for testing.
